module.exports =
  [{
    "code": 86,
    "tw": "中國",
    "en": "China",
    "locale": "CN",
    "zh": "中国",
    "nameIndex": "Z",
    "pinyin": "zhongguo"
  }, {
    "code": 244,
    "tw": "安哥拉",
    "en": "Angola",
    "locale": "AO",
    "zh": "安哥拉",
    "nameIndex": "A",
    "pinyin": "angela"
  }, {
    "code": 93,
    "tw": "阿富汗",
    "en": "Afghanistan",
    "locale": "AF",
    "zh": "阿富汗",
    "nameIndex": "A",
    "pinyin": "afuhan"
  }, {
    "code": 355,
    "tw": "阿爾巴尼亞",
    "en": "Albania",
    "locale": "AL",
    "zh": "阿尔巴尼亚",
    "nameIndex": "A",
    "pinyin": "aerbaniya"
  }, {
    "code": 213,
    "tw": "阿爾及利亞",
    "en": "Algeria",
    "locale": "DZ",
    "zh": "阿尔及利亚",
    "nameIndex": "A",
    "pinyin": "aerjiliya"
  }, {
    "code": 376,
    "tw": "安道爾共和國",
    "en": "Andorra",
    "locale": "AD",
    "zh": "安道尔共和国",
    "nameIndex": "A",
    "pinyin": "andaoergongheguo"
  }, {
    "code": 1264,
    "tw": "安圭拉島",
    "en": "Anguilla",
    "locale": "AI",
    "zh": "安圭拉岛",
    "nameIndex": "A",
    "pinyin": "anguiladao"
  }, {
    "code": 1268,
    "tw": "安提瓜和巴布達",
    "en": "Antigua and Barbuda",
    "locale": "AG",
    "zh": "安提瓜和巴布达",
    "nameIndex": "A",
    "pinyin": "antiguahebabuda"
  }, {
    "code": 54,
    "tw": "阿根廷",
    "en": "Argentina",
    "locale": "AR",
    "zh": "阿根廷",
    "nameIndex": "A",
    "pinyin": "agenting"
  }, {
    "code": 374,
    "tw": "亞美尼亞",
    "en": "Armenia",
    "locale": "AM",
    "zh": "亚美尼亚",
    "nameIndex": "Y",
    "pinyin": "yameiniya"
  }, {
    "code": 247,
    "tw": "阿森松",
    "en": "Ascension",
    "locale": " ",
    "zh": "阿森松",
    "nameIndex": "A",
    "pinyin": "asensong"
  }, {
    "code": 61,
    "tw": "澳大利亞",
    "en": "Australia",
    "locale": "AU",
    "zh": "澳大利亚",
    "nameIndex": "A",
    "pinyin": "aodaliya"
  }, {
    "code": 43,
    "tw": "奧地利",
    "en": "Austria",
    "locale": "AT",
    "zh": "奥地利",
    "nameIndex": "A",
    "pinyin": "aodili"
  }, {
    "code": 994,
    "tw": "阿塞拜疆",
    "en": "Azerbaijan",
    "locale": "AZ",
    "zh": "阿塞拜疆",
    "nameIndex": "A",
    "pinyin": "asaibaijiang"
  }, {
    "code": 1242,
    "tw": "巴哈馬",
    "en": "Bahamas",
    "locale": "BS",
    "zh": "巴哈马",
    "nameIndex": "B",
    "pinyin": "bahama"
  }, {
    "code": 973,
    "tw": "巴林",
    "en": "Bahrain",
    "locale": "BH",
    "zh": "巴林",
    "nameIndex": "B",
    "pinyin": "balin"
  }, {
    "code": 880,
    "tw": "孟加拉國",
    "en": "Bangladesh",
    "locale": "BD",
    "zh": "孟加拉国",
    "nameIndex": "M",
    "pinyin": "mengjialaguo"
  }, {
    "code": 1246,
    "tw": "巴巴多斯",
    "en": "Barbados",
    "locale": "BB",
    "zh": "巴巴多斯",
    "nameIndex": "B",
    "pinyin": "babaduosi"
  }, {
    "code": 375,
    "tw": "白俄羅斯",
    "en": "Belarus",
    "locale": "BY",
    "zh": "白俄罗斯",
    "nameIndex": "B",
    "pinyin": "baieluosi"
  }, {
    "code": 32,
    "tw": "比利時",
    "en": "Belgium",
    "locale": "BE",
    "zh": "比利时",
    "nameIndex": "B",
    "pinyin": "bilishi"
  }, {
    "code": 501,
    "tw": "伯利茲",
    "en": "Belize",
    "locale": "BZ",
    "zh": "伯利兹",
    "nameIndex": "B",
    "pinyin": "bolizi"
  }, {
    "code": 229,
    "tw": "貝寧",
    "en": "Benin",
    "locale": "BJ",
    "zh": "贝宁",
    "nameIndex": "B",
    "pinyin": "beining"
  }, {
    "code": 1441,
    "tw": "百慕達群島",
    "en": "Bermuda Is.",
    "locale": "BM",
    "zh": "百慕大群岛",
    "nameIndex": "B",
    "pinyin": "baimudaqundao"
  }, {
    "code": 591,
    "tw": "玻利維亞",
    "en": "Bolivia",
    "locale": "BO",
    "zh": "玻利维亚",
    "nameIndex": "B",
    "pinyin": "boliweiya"
  }, {
    "code": 267,
    "tw": "博茨瓦納",
    "en": "Botswana",
    "locale": "BW",
    "zh": "博茨瓦纳",
    "nameIndex": "B",
    "pinyin": "bociwana"
  }, {
    "code": 55,
    "tw": "巴西",
    "en": "Brazil",
    "locale": "BR",
    "zh": "巴西",
    "nameIndex": "B",
    "pinyin": "baxi"
  }, {
    "code": 673,
    "tw": "文萊",
    "en": "Brunei",
    "locale": "BN",
    "zh": "文莱",
    "nameIndex": "W",
    "pinyin": "wenlai"
  }, {
    "code": 359,
    "tw": "保加利亞",
    "en": "Bulgaria",
    "locale": "BG",
    "zh": "保加利亚",
    "nameIndex": "B",
    "pinyin": "baojialiya"
  }, {
    "code": 226,
    "tw": "布基納法索",
    "en": "Burkina-faso",
    "locale": "BF",
    "zh": "布基纳法索",
    "nameIndex": "B",
    "pinyin": "bujinafasuo"
  }, {
    "code": 95,
    "tw": "緬甸",
    "en": "Burma",
    "locale": "MM",
    "zh": "缅甸",
    "nameIndex": "M",
    "pinyin": "miandian"
  }, {
    "code": 257,
    "tw": "布隆迪",
    "en": "Burundi",
    "locale": "BI",
    "zh": "布隆迪",
    "nameIndex": "B",
    "pinyin": "bulongdi"
  }, {
    "code": 237,
    "tw": "喀麥隆",
    "en": "Cameroon",
    "locale": "CM",
    "zh": "喀麦隆",
    "nameIndex": "K",
    "pinyin": "kamailong"
  }, {
    "code": 1,
    "tw": "加拿大",
    "en": "Canada",
    "locale": "CA",
    "zh": "加拿大",
    "nameIndex": "J",
    "pinyin": "jianada"
  }, {
    "code": 1345,
    "tw": "開曼群島",
    "en": "Cayman Is.",
    "locale": " ",
    "zh": "开曼群岛",
    "nameIndex": "K",
    "pinyin": "kaimanqundao"
  }, {
    "code": 236,
    "tw": "中非共和國",
    "en": "Central African Republic",
    "locale": "CF",
    "zh": "中非共和国",
    "nameIndex": "Z",
    "pinyin": "zhongfeigongheguo"
  }, {
    "code": 235,
    "tw": "乍得",
    "en": "Chad",
    "locale": "TD",
    "zh": "乍得",
    "nameIndex": "Z",
    "pinyin": "zhade"
  }, {
    "code": 56,
    "tw": "智利",
    "en": "Chile",
    "locale": "CL",
    "zh": "智利",
    "nameIndex": "Z",
    "pinyin": "zhili"
  }, {
    "code": 57,
    "tw": "哥倫比亞",
    "en": "Colombia",
    "locale": "CO",
    "zh": "哥伦比亚",
    "nameIndex": "G",
    "pinyin": "gelunbiya"
  }, {
    "code": 242,
    "tw": "剛果",
    "en": "Congo",
    "locale": "CG",
    "zh": "刚果",
    "nameIndex": "G",
    "pinyin": "gangguo"
  }, {
    "code": 682,
    "tw": "庫克群島",
    "en": "Cook Is.",
    "locale": "CK",
    "zh": "库克群岛",
    "nameIndex": "K",
    "pinyin": "kukequndao"
  }, {
    "code": 506,
    "tw": "哥斯達黎加",
    "en": "Costa Rica",
    "locale": "CR",
    "zh": "哥斯达黎加",
    "nameIndex": "G",
    "pinyin": "gesidalijia"
  }, {
    "code": 53,
    "tw": "古巴",
    "en": "Cuba",
    "locale": "CU",
    "zh": "古巴",
    "nameIndex": "G",
    "pinyin": "guba"
  }, {
    "code": 357,
    "tw": "塞浦路斯",
    "en": "Cyprus",
    "locale": "CY",
    "zh": "塞浦路斯",
    "nameIndex": "S",
    "pinyin": "saipulusi"
  }, {
    "code": 420,
    "tw": "捷克",
    "en": "Czech Republic",
    "locale": "CZ",
    "zh": "捷克",
    "nameIndex": "J",
    "pinyin": "jieke"
  }, {
    "code": 45,
    "tw": "丹麥",
    "en": "Denmark",
    "locale": "DK",
    "zh": "丹麦",
    "nameIndex": "D",
    "pinyin": "danmai"
  }, {
    "code": 253,
    "tw": "吉布堤",
    "en": "Djibouti",
    "locale": "DJ",
    "zh": "吉布提",
    "nameIndex": "J",
    "pinyin": "jibuti"
  }, {
    "code": 1890,
    "tw": "多明尼加共和國共和國",
    "en": "Dominica Rep.",
    "locale": "DO",
    "zh": "多米尼加共和国",
    "nameIndex": "D",
    "pinyin": "duominijiagongheguo"
  }, {
    "code": 593,
    "tw": "厄瓜多爾",
    "en": "Ecuador",
    "locale": "EC",
    "zh": "厄瓜多尔",
    "nameIndex": "E",
    "pinyin": "eguaduoer"
  }, {
    "code": 20,
    "tw": "埃及",
    "en": "Egypt",
    "locale": "EG",
    "zh": "埃及",
    "nameIndex": "A",
    "pinyin": "aiji"
  }, {
    "code": 503,
    "tw": "薩爾瓦多",
    "en": "EI Salvador",
    "locale": "SV",
    "zh": "萨尔瓦多",
    "nameIndex": "S",
    "pinyin": "saerwaduo"
  }, {
    "code": 372,
    "tw": "愛沙尼亞",
    "en": "Estonia",
    "locale": "EE",
    "zh": "爱沙尼亚",
    "nameIndex": "A",
    "pinyin": "aishaniya"
  }, {
    "code": 251,
    "tw": "埃塞俄比亞",
    "en": "Ethiopia",
    "locale": "ET",
    "zh": "埃塞俄比亚",
    "nameIndex": "A",
    "pinyin": "aisaiebiya"
  }, {
    "code": 679,
    "tw": "斐濟",
    "en": "Fiji",
    "locale": "FJ",
    "zh": "斐济",
    "nameIndex": "F",
    "pinyin": "feiji"
  }, {
    "code": 358,
    "tw": "芬蘭",
    "en": "Finland",
    "locale": "FI",
    "zh": "芬兰",
    "nameIndex": "F",
    "pinyin": "fenlan"
  }, {
    "code": 33,
    "tw": "法國",
    "en": "France",
    "locale": "FR",
    "zh": "法国",
    "nameIndex": "F",
    "pinyin": "faguo"
  }, {
    "code": 594,
    "tw": "法屬圭亞那",
    "en": "French Guiana",
    "locale": "GF",
    "zh": "法属圭亚那",
    "nameIndex": "F",
    "pinyin": "fashuguiyana"
  }, {
    "code": 241,
    "tw": "加蓬",
    "en": "Gabon",
    "locale": "GA",
    "zh": "加蓬",
    "nameIndex": "J",
    "pinyin": "jiapeng"
  }, {
    "code": 220,
    "tw": "岡比亞",
    "en": "Gambia",
    "locale": "GM",
    "zh": "冈比亚",
    "nameIndex": "G",
    "pinyin": "gangbiya"
  }, {
    "code": 995,
    "tw": "格魯吉亞",
    "en": "Georgia",
    "locale": "GE",
    "zh": "格鲁吉亚",
    "nameIndex": "G",
    "pinyin": "gelujiya"
  }, {
    "code": 49,
    "tw": "德國",
    "en": "Germany",
    "locale": "DE",
    "zh": "德国",
    "nameIndex": "D",
    "pinyin": "deguo"
  }, {
    "code": 233,
    "tw": "加納",
    "en": "Ghana",
    "locale": "GH",
    "zh": "加纳",
    "nameIndex": "J",
    "pinyin": "jiana"
  }, {
    "code": 350,
    "tw": "直布羅陀",
    "en": "Gibraltar",
    "locale": "GI",
    "zh": "直布罗陀",
    "nameIndex": "Z",
    "pinyin": "zhibuluotuo"
  }, {
    "code": 30,
    "tw": "希臘",
    "en": "Greece",
    "locale": "GR",
    "zh": "希腊",
    "nameIndex": "X",
    "pinyin": "xila"
  }, {
    "code": 1809,
    "tw": "格林納達",
    "en": "Grenada",
    "locale": "GD",
    "zh": "格林纳达",
    "nameIndex": "G",
    "pinyin": "gelinnada"
  }, {
    "code": 1671,
    "tw": "關島",
    "en": "Guam",
    "locale": "GU",
    "zh": "关岛",
    "nameIndex": "G",
    "pinyin": "guandao"
  }, {
    "code": 502,
    "tw": "危地馬拉",
    "en": "Guatemala",
    "locale": "GT",
    "zh": "危地马拉",
    "nameIndex": "W",
    "pinyin": "weidimala"
  }, {
    "code": 224,
    "tw": "幾內亞",
    "en": "Guinea",
    "locale": "GN",
    "zh": "几内亚",
    "nameIndex": "J",
    "pinyin": "jineiya"
  }, {
    "code": 592,
    "tw": "圭亞那",
    "en": "Guyana",
    "locale": "GY",
    "zh": "圭亚那",
    "nameIndex": "G",
    "pinyin": "guiyana"
  }, {
    "code": 509,
    "tw": "海地",
    "en": "Haiti",
    "locale": "HT",
    "zh": "海地",
    "nameIndex": "H",
    "pinyin": "haidi"
  }, {
    "code": 504,
    "tw": "洪都拉斯",
    "en": "Honduras",
    "locale": "HN",
    "zh": "洪都拉斯",
    "nameIndex": "H",
    "pinyin": "hongdoulasi"
  }, {
    "code": 852,
    "tw": "中國香港",
    "en": "Hongkong",
    "locale": "HK",
    "zh": "中国香港",
    "nameIndex": "Z",
    "pinyin": "zhongguoxianggang"
  }, {
    "code": 36,
    "tw": "匈牙利",
    "en": "Hungary",
    "locale": "HU",
    "zh": "匈牙利",
    "nameIndex": "X",
    "pinyin": "xiongyali"
  }, {
    "code": 354,
    "tw": "冰島",
    "en": "Iceland",
    "locale": "IS",
    "zh": "冰岛",
    "nameIndex": "B",
    "pinyin": "bingdao"
  }, {
    "code": 91,
    "tw": "印度",
    "en": "India",
    "locale": "IN",
    "zh": "印度",
    "nameIndex": "Y",
    "pinyin": "yindu"
  }, {
    "code": 62,
    "tw": "印度尼西亞",
    "en": "Indonesia",
    "locale": "ID",
    "zh": "印度尼西亚",
    "nameIndex": "Y",
    "pinyin": "yindunixiya"
  }, {
    "code": 98,
    "tw": "伊朗",
    "en": "Iran",
    "locale": "IR",
    "zh": "伊朗",
    "nameIndex": "Y",
    "pinyin": "yilang"
  }, {
    "code": 964,
    "tw": "伊拉克",
    "en": "Iraq",
    "locale": "IQ",
    "zh": "伊拉克",
    "nameIndex": "Y",
    "pinyin": "yilake"
  }, {
    "code": 353,
    "tw": "愛爾蘭",
    "en": "Ireland",
    "locale": "IE",
    "zh": "爱尔兰",
    "nameIndex": "A",
    "pinyin": "aierlan"
  }, {
    "code": 972,
    "tw": "以色列",
    "en": "Israel",
    "locale": "IL",
    "zh": "以色列",
    "nameIndex": "Y",
    "pinyin": "yiselie"
  }, {
    "code": 39,
    "tw": "意大利",
    "en": "Italy",
    "locale": "IT",
    "zh": "意大利",
    "nameIndex": "Y",
    "pinyin": "yidali"
  }, {
    "code": 225,
    "tw": "科特迪瓦",
    "en": "Ivory Coast",
    "locale": " ",
    "zh": "科特迪瓦",
    "nameIndex": "K",
    "pinyin": "ketediwa"
  }, {
    "code": 1876,
    "tw": "牙買加",
    "en": "Jamaica",
    "locale": "JM",
    "zh": "牙买加",
    "nameIndex": "Y",
    "pinyin": "yamaijia"
  }, {
    "code": 81,
    "tw": "日本",
    "en": "Japan",
    "locale": "JP",
    "zh": "日本",
    "nameIndex": "R",
    "pinyin": "riben"
  }, {
    "code": 962,
    "tw": "約旦",
    "en": "Jordan",
    "locale": "JO",
    "zh": "约旦",
    "nameIndex": "Y",
    "pinyin": "yuedan"
  }, {
    "code": 855,
    "tw": "柬埔寨",
    "en": "Kampuchea (Cambodia )",
    "locale": "KH",
    "zh": "柬埔寨",
    "nameIndex": "J",
    "pinyin": "jianpuzhai"
  }, {
    "code": 327,
    "tw": "哈薩克",
    "en": "Kazakstan",
    "locale": "KZ",
    "zh": "哈萨克斯坦",
    "nameIndex": "H",
    "pinyin": "hasakesitan"
  }, {
    "code": 254,
    "tw": "肯雅",
    "en": "Kenya",
    "locale": "KE",
    "zh": "肯尼亚",
    "nameIndex": "K",
    "pinyin": "kenniya"
  }, {
    "code": 82,
    "tw": "韓國",
    "en": "Korea",
    "locale": "KR",
    "zh": "韩国",
    "nameIndex": "H",
    "pinyin": "hanguo"
  }, {
    "code": 965,
    "tw": "科威特",
    "en": "Kuwait",
    "locale": "KW",
    "zh": "科威特",
    "nameIndex": "K",
    "pinyin": "keweite"
  }, {
    "code": 331,
    "tw": "吉爾吉斯坦",
    "en": "Kyrgyzstan",
    "locale": "KG",
    "zh": "吉尔吉斯坦",
    "nameIndex": "J",
    "pinyin": "jierjisitan"
  }, {
    "code": 856,
    "tw": "寮國",
    "en": "Laos",
    "locale": "LA",
    "zh": "老挝",
    "nameIndex": "L",
    "pinyin": "laozhua"
  }, {
    "code": 371,
    "tw": "拉脫維亞",
    "en": "Latvia",
    "locale": "LV",
    "zh": "拉脱维亚",
    "nameIndex": "L",
    "pinyin": "latuoweiya"
  }, {
    "code": 961,
    "tw": "黎巴嫩",
    "en": "Lebanon",
    "locale": "LB",
    "zh": "黎巴嫩",
    "nameIndex": "L",
    "pinyin": "libanen"
  }, {
    "code": 266,
    "tw": "萊索托",
    "en": "Lesotho",
    "locale": "LS",
    "zh": "莱索托",
    "nameIndex": "L",
    "pinyin": "laisuotuo"
  }, {
    "code": 231,
    "tw": "利比里亞",
    "en": "Liberia",
    "locale": "LR",
    "zh": "利比里亚",
    "nameIndex": "L",
    "pinyin": "libiliya"
  }, {
    "code": 218,
    "tw": "利比亞",
    "en": "Libya",
    "locale": "LY",
    "zh": "利比亚",
    "nameIndex": "L",
    "pinyin": "libiya"
  }, {
    "code": 423,
    "tw": "列支敦士登",
    "en": "Liechtenstein",
    "locale": "LI",
    "zh": "列支敦士登",
    "nameIndex": "L",
    "pinyin": "liezhidunshideng"
  }, {
    "code": 370,
    "tw": "立陶宛",
    "en": "Lithuania",
    "locale": "LT",
    "zh": "立陶宛",
    "nameIndex": "L",
    "pinyin": "litaowan"
  }, {
    "code": 352,
    "tw": "盧森堡",
    "en": "Luxembourg",
    "locale": "LU",
    "zh": "卢森堡",
    "nameIndex": "L",
    "pinyin": "lusenbao"
  }, {
    "code": 853,
    "tw": "中國澳門",
    "en": "Macao",
    "locale": "MO",
    "zh": "中国澳门",
    "nameIndex": "Z",
    "pinyin": "zhongguoaomen"
  }, {
    "code": 261,
    "tw": "馬達加斯加",
    "en": "Madagascar",
    "locale": "MG",
    "zh": "马达加斯加",
    "nameIndex": "M",
    "pinyin": "madajiasijia"
  }, {
    "code": 265,
    "tw": "馬拉維",
    "en": "Malawi",
    "locale": "MW",
    "zh": "马拉维",
    "nameIndex": "M",
    "pinyin": "malawei"
  }, {
    "code": 60,
    "tw": "馬來西亞",
    "en": "Malaysia",
    "locale": "MY",
    "zh": "马来西亚",
    "nameIndex": "M",
    "pinyin": "malaixiya"
  }, {
    "code": 960,
    "tw": "馬爾代夫",
    "en": "Maldives",
    "locale": "MV",
    "zh": "马尔代夫",
    "nameIndex": "M",
    "pinyin": "maerdaifu"
  }, {
    "code": 223,
    "tw": "馬里",
    "en": "Mali",
    "locale": "ML",
    "zh": "马里",
    "nameIndex": "M",
    "pinyin": "mali"
  }, {
    "code": 356,
    "tw": "馬爾他",
    "en": "Malta",
    "locale": "MT",
    "zh": "马耳他",
    "nameIndex": "M",
    "pinyin": "maerta"
  }, {
    "code": 1670,
    "tw": "馬里亞那群島",
    "en": "Mariana Is",
    "locale": " ",
    "zh": "马里亚那群岛",
    "nameIndex": "M",
    "pinyin": "maliyanaqundao"
  }, {
    "code": 596,
    "tw": "馬提尼克島",
    "en": "Martinique",
    "locale": " ",
    "zh": "马提尼克",
    "nameIndex": "M",
    "pinyin": "matinike"
  }, {
    "code": 230,
    "tw": "毛里裘斯",
    "en": "Mauritius",
    "locale": "MU",
    "zh": "毛里求斯",
    "nameIndex": "M",
    "pinyin": "maoliqiusi"
  }, {
    "code": 52,
    "tw": "墨西哥",
    "en": "Mexico",
    "locale": "MX",
    "zh": "墨西哥",
    "nameIndex": "M",
    "pinyin": "moxige"
  }, {
    "code": 373,
    "tw": "摩爾多瓦",
    "en": "Moldova, Republic of",
    "locale": "MD",
    "zh": "摩尔多瓦",
    "nameIndex": "M",
    "pinyin": "moerduowa"
  }, {
    "code": 377,
    "tw": "摩納哥",
    "en": "Monaco",
    "locale": "MC",
    "zh": "摩纳哥",
    "nameIndex": "M",
    "pinyin": "monage"
  }, {
    "code": 976,
    "tw": "蒙古",
    "en": "Mongolia",
    "locale": "MN",
    "zh": "蒙古",
    "nameIndex": "M",
    "pinyin": "menggu"
  }, {
    "code": 1664,
    "tw": "蒙特塞拉特島",
    "en": "Montserrat Is",
    "locale": "MS",
    "zh": "蒙特塞拉特岛",
    "nameIndex": "M",
    "pinyin": "mengtesailatedao"
  }, {
    "code": 212,
    "tw": "摩洛哥",
    "en": "Morocco",
    "locale": "MA",
    "zh": "摩洛哥",
    "nameIndex": "M",
    "pinyin": "moluoge"
  }, {
    "code": 258,
    "tw": "莫桑比克",
    "en": "Mozambique",
    "locale": "MZ",
    "zh": "莫桑比克",
    "nameIndex": "M",
    "pinyin": "mosangbike"
  }, {
    "code": 264,
    "tw": "納米比亞",
    "en": "Namibia",
    "locale": "NA",
    "zh": "纳米比亚",
    "nameIndex": "N",
    "pinyin": "namibiya"
  }, {
    "code": 674,
    "tw": "瑙魯",
    "en": "Nauru",
    "locale": "NR",
    "zh": "瑙鲁",
    "nameIndex": "N",
    "pinyin": "naolu"
  }, {
    "code": 977,
    "tw": "尼泊爾",
    "en": "Nepal",
    "locale": "NP",
    "zh": "尼泊尔",
    "nameIndex": "N",
    "pinyin": "niboer"
  }, {
    "code": 599,
    "tw": "荷屬安地列斯",
    "en": "Netheriands Antilles",
    "locale": " ",
    "zh": "荷属安的列斯",
    "nameIndex": "H",
    "pinyin": "heshuandeliesi"
  }, {
    "code": 31,
    "tw": "荷蘭",
    "en": "Netherlands",
    "locale": "NL",
    "zh": "荷兰",
    "nameIndex": "H",
    "pinyin": "helan"
  }, {
    "code": 64,
    "tw": "新西蘭",
    "en": "New Zealand",
    "locale": "NZ",
    "zh": "新西兰",
    "nameIndex": "X",
    "pinyin": "xinxilan"
  }, {
    "code": 505,
    "tw": "尼加拉瓜",
    "en": "Nicaragua",
    "locale": "NI",
    "zh": "尼加拉瓜",
    "nameIndex": "N",
    "pinyin": "nijialagua"
  }, {
    "code": 227,
    "tw": "尼日爾",
    "en": "Niger",
    "locale": "NE",
    "zh": "尼日尔",
    "nameIndex": "N",
    "pinyin": "nirier"
  }, {
    "code": 234,
    "tw": "尼日利亞",
    "en": "Nigeria",
    "locale": "NG",
    "zh": "尼日利亚",
    "nameIndex": "N",
    "pinyin": "niriliya"
  }, {
    "code": 850,
    "tw": "朝鮮",
    "en": "North Korea",
    "locale": "KP",
    "zh": "朝鲜",
    "nameIndex": "Z",
    "pinyin": "zhaoxian"
  }, {
    "code": 47,
    "tw": "挪威",
    "en": "Norway",
    "locale": "NO",
    "zh": "挪威",
    "nameIndex": "N",
    "pinyin": "nuowei"
  }, {
    "code": 968,
    "tw": "阿曼",
    "en": "Oman",
    "locale": "OM",
    "zh": "阿曼",
    "nameIndex": "A",
    "pinyin": "aman"
  }, {
    "code": 92,
    "tw": "巴基斯坦",
    "en": "Pakistan",
    "locale": "PK",
    "zh": "巴基斯坦",
    "nameIndex": "B",
    "pinyin": "bajisitan"
  }, {
    "code": 507,
    "tw": "巴拿馬",
    "en": "Panama",
    "locale": "PA",
    "zh": "巴拿马",
    "nameIndex": "B",
    "pinyin": "banama"
  }, {
    "code": 675,
    "tw": "巴布亞新畿內亞",
    "en": "Papua New Cuinea",
    "locale": "PG",
    "zh": "巴布亚新几内亚",
    "nameIndex": "B",
    "pinyin": "babuyaxinjineiya"
  }, {
    "code": 595,
    "tw": "巴拉圭",
    "en": "Paraguay",
    "locale": "PY",
    "zh": "巴拉圭",
    "nameIndex": "B",
    "pinyin": "balagui"
  }, {
    "code": 51,
    "tw": "秘魯",
    "en": "Peru",
    "locale": "PE",
    "zh": "秘鲁",
    "nameIndex": "B",
    "pinyin": "bilu"
  }, {
    "code": 63,
    "tw": "菲律賓",
    "en": "Philippines",
    "locale": "PH",
    "zh": "菲律宾",
    "nameIndex": "F",
    "pinyin": "feilvbin"
  }, {
    "code": 48,
    "tw": "波蘭",
    "en": "Poland",
    "locale": "PL",
    "zh": "波兰",
    "nameIndex": "B",
    "pinyin": "bolan"
  }, {
    "code": 689,
    "tw": "法屬玻利尼西亞",
    "en": "French Polynesia",
    "locale": "PF",
    "zh": "法属玻利尼西亚",
    "nameIndex": "F",
    "pinyin": "fashubolinixiya"
  }, {
    "code": 351,
    "tw": "葡萄牙",
    "en": "Portugal",
    "locale": "PT",
    "zh": "葡萄牙",
    "nameIndex": "P",
    "pinyin": "putaoya"
  }, {
    "code": 1787,
    "tw": "波多黎各",
    "en": "Puerto Rico",
    "locale": "PR",
    "zh": "波多黎各",
    "nameIndex": "B",
    "pinyin": "boduolige"
  }, {
    "code": 974,
    "tw": "卡塔爾",
    "en": "Qatar",
    "locale": "QA",
    "zh": "卡塔尔",
    "nameIndex": "Q",
    "pinyin": "qiataer"
  }, {
    "code": 262,
    "tw": "留尼旺",
    "en": "Reunion",
    "locale": " ",
    "zh": "留尼旺",
    "nameIndex": "L",
    "pinyin": "liuniwang"
  }, {
    "code": 40,
    "tw": "羅馬尼亞",
    "en": "Romania",
    "locale": "RO",
    "zh": "罗马尼亚",
    "nameIndex": "L",
    "pinyin": "luomaniya"
  }, {
    "code": 7,
    "tw": "俄羅斯",
    "en": "Russia",
    "locale": "RU",
    "zh": "俄罗斯",
    "nameIndex": "E",
    "pinyin": "eluosi"
  }, {
    "code": 1758,
    "tw": "聖盧西亞",
    "en": "Saint Lueia",
    "locale": "LC",
    "zh": "圣卢西亚",
    "nameIndex": "S",
    "pinyin": "shengluxiya"
  }, {
    "code": 1784,
    "tw": "聖文森特島",
    "en": "Saint Vincent",
    "locale": "VC",
    "zh": "圣文森特岛",
    "nameIndex": "S",
    "pinyin": "shengwensentedao"
  }, {
    "code": 684,
    "tw": "東薩摩亞(美)",
    "en": "Samoa Eastern",
    "locale": " ",
    "zh": "东萨摩亚(美)",
    "nameIndex": "D",
    "pinyin": "dongsamoya(mei)"
  }, {
    "code": 685,
    "tw": "西薩摩亞",
    "en": "Samoa Western",
    "locale": " ",
    "zh": "西萨摩亚",
    "nameIndex": "X",
    "pinyin": "xisamoya"
  }, {
    "code": 378,
    "tw": "聖馬力諾",
    "en": "San Marino",
    "locale": "SM",
    "zh": "圣马力诺",
    "nameIndex": "S",
    "pinyin": "shengmalinuo"
  }, {
    "code": 239,
    "tw": "聖多美和普林西比",
    "en": "Sao Tome and Principe",
    "locale": "ST",
    "zh": "圣多美和普林西比",
    "nameIndex": "S",
    "pinyin": "shengduomeihepulinxibi"
  }, {
    "code": 966,
    "tw": "沙地阿拉伯",
    "en": "Saudi Arabia",
    "locale": "SA",
    "zh": "沙特阿拉伯",
    "nameIndex": "S",
    "pinyin": "shatealabo"
  }, {
    "code": 221,
    "tw": "塞內加爾",
    "en": "Senegal",
    "locale": "SN",
    "zh": "塞内加尔",
    "nameIndex": "S",
    "pinyin": "saineijiaer"
  }, {
    "code": 248,
    "tw": "塞舌爾",
    "en": "Seychelles",
    "locale": "SC",
    "zh": "塞舌尔",
    "nameIndex": "S",
    "pinyin": "saisheer"
  }, {
    "code": 232,
    "tw": "塞拉利昂",
    "en": "Sierra Leone",
    "locale": "SL",
    "zh": "塞拉利昂",
    "nameIndex": "S",
    "pinyin": "sailaliang"
  }, {
    "code": 65,
    "tw": "新加坡",
    "en": "Singapore",
    "locale": "SG",
    "zh": "新加坡",
    "nameIndex": "X",
    "pinyin": "xinjiapo"
  }, {
    "code": 421,
    "tw": "斯洛伐克",
    "en": "Slovakia",
    "locale": "SK",
    "zh": "斯洛伐克",
    "nameIndex": "S",
    "pinyin": "siluofake"
  }, {
    "code": 386,
    "tw": "斯洛文尼亞",
    "en": "Slovenia",
    "locale": "SI",
    "zh": "斯洛文尼亚",
    "nameIndex": "S",
    "pinyin": "siluowenniya"
  }, {
    "code": 677,
    "tw": "所羅門群島",
    "en": "Solomon Is",
    "locale": "SB",
    "zh": "所罗门群岛",
    "nameIndex": "S",
    "pinyin": "suoluomenqundao"
  }, {
    "code": 252,
    "tw": "索馬里",
    "en": "Somali",
    "locale": "SO",
    "zh": "索马里",
    "nameIndex": "S",
    "pinyin": "suomali"
  }, {
    "code": 27,
    "tw": "南非",
    "en": "South Africa",
    "locale": "ZA",
    "zh": "南非",
    "nameIndex": "N",
    "pinyin": "nanfei"
  }, {
    "code": 34,
    "tw": "西班牙",
    "en": "Spain",
    "locale": "ES",
    "zh": "西班牙",
    "nameIndex": "X",
    "pinyin": "xibanya"
  }, {
    "code": 94,
    "tw": "斯裡蘭卡",
    "en": "Sri Lanka",
    "locale": "LK",
    "zh": "斯里兰卡",
    "nameIndex": "S",
    "pinyin": "sililanqia"
  }, {
    "code": 1758,
    "tw": "聖盧西亞",
    "en": "St.Lucia",
    "locale": "LC",
    "zh": "圣卢西亚",
    "nameIndex": "S",
    "pinyin": "shengluxiya"
  }, {
    "code": 1784,
    "tw": "聖文森特",
    "en": "St.Vincent",
    "locale": "VC",
    "zh": "圣文森特",
    "nameIndex": "S",
    "pinyin": "shengwensente"
  }, {
    "code": 249,
    "tw": "蘇丹",
    "en": "Sudan",
    "locale": "SD",
    "zh": "苏丹",
    "nameIndex": "S",
    "pinyin": "sudan"
  }, {
    "code": 597,
    "tw": "蘇里南",
    "en": "Suriname",
    "locale": "SR",
    "zh": "苏里南",
    "nameIndex": "S",
    "pinyin": "sulinan"
  }, {
    "code": 268,
    "tw": "斯威士蘭",
    "en": "Swaziland",
    "locale": "SZ",
    "zh": "斯威士兰",
    "nameIndex": "S",
    "pinyin": "siweishilan"
  }, {
    "code": 46,
    "tw": "瑞典",
    "en": "Sweden",
    "locale": "SE",
    "zh": "瑞典",
    "nameIndex": "R",
    "pinyin": "ruidian"
  }, {
    "code": 41,
    "tw": "瑞士",
    "en": "Switzerland",
    "locale": "CH",
    "zh": "瑞士",
    "nameIndex": "R",
    "pinyin": "ruishi"
  }, {
    "code": 963,
    "tw": "敘利亞",
    "en": "Syria",
    "locale": "SY",
    "zh": "叙利亚",
    "nameIndex": "X",
    "pinyin": "xuliya"
  }, {
    "code": 886,
    "tw": "中國台灣",
    "en": "Taiwan",
    "locale": "TW",
    "zh": "中国台湾",
    "nameIndex": "Z",
    "pinyin": "zhongguotaiwan"
  }, {
    "code": 992,
    "tw": "塔吉克",
    "en": "Tajikstan",
    "locale": "TJ",
    "zh": "塔吉克斯坦",
    "nameIndex": "T",
    "pinyin": "tajikesitan"
  }, {
    "code": 255,
    "tw": "坦桑尼亞",
    "en": "Tanzania",
    "locale": "TZ",
    "zh": "坦桑尼亚",
    "nameIndex": "T",
    "pinyin": "tansangniya"
  }, {
    "code": 66,
    "tw": "泰國",
    "en": "Thailand",
    "locale": "TH",
    "zh": "泰国",
    "nameIndex": "T",
    "pinyin": "taiguo"
  }, {
    "code": 228,
    "tw": "多哥",
    "en": "Togo",
    "locale": "TG",
    "zh": "多哥",
    "nameIndex": "D",
    "pinyin": "duoge"
  }, {
    "code": 676,
    "tw": "湯加",
    "en": "Tonga",
    "locale": "TO",
    "zh": "汤加",
    "nameIndex": "T",
    "pinyin": "tangjia"
  }, {
    "code": 1809,
    "tw": "特立尼達和多巴哥",
    "en": "Trinidad and Tobago",
    "locale": "TT",
    "zh": "特立尼达和多巴哥",
    "nameIndex": "T",
    "pinyin": "telinidaheduobage"
  }, {
    "code": 216,
    "tw": "突尼斯",
    "en": "Tunisia",
    "locale": "TN",
    "zh": "突尼斯",
    "nameIndex": "T",
    "pinyin": "tunisi"
  }, {
    "code": 90,
    "tw": "土耳其",
    "en": "Turkey",
    "locale": "TR",
    "zh": "土耳其",
    "nameIndex": "T",
    "pinyin": "tuerqi"
  }, {
    "code": 993,
    "tw": "土庫曼",
    "en": "Turkmenistan",
    "locale": "TM",
    "zh": "土库曼斯坦",
    "nameIndex": "T",
    "pinyin": "tukumansitan"
  }, {
    "code": 256,
    "tw": "烏幹達",
    "en": "Uganda",
    "locale": "UG",
    "zh": "乌干达",
    "nameIndex": "W",
    "pinyin": "wuganda"
  }, {
    "code": 380,
    "tw": "烏克蘭",
    "en": "Ukraine",
    "locale": "UA",
    "zh": "乌克兰",
    "nameIndex": "W",
    "pinyin": "wukelan"
  }, {
    "code": 971,
    "tw": "阿拉伯聯合酋長國",
    "en": "United Arab Emirates",
    "locale": "AE",
    "zh": "阿拉伯联合酋长国",
    "nameIndex": "A",
    "pinyin": "alabolianheqiuchangguo"
  }, {
    "code": 44,
    "tw": "英國",
    "en": "United Kiongdom",
    "locale": "GB",
    "zh": "英国",
    "nameIndex": "Y",
    "pinyin": "yingguo"
  }, {
    "code": 1,
    "tw": "美國",
    "en": "United States of America",
    "locale": "US",
    "zh": "美国",
    "nameIndex": "M",
    "pinyin": "meiguo"
  }, {
    "code": 598,
    "tw": "烏拉圭",
    "en": "Uruguay",
    "locale": "UY",
    "zh": "乌拉圭",
    "nameIndex": "W",
    "pinyin": "wulagui"
  }, {
    "code": 233,
    "tw": "烏茲別克",
    "en": "Uzbekistan",
    "locale": "UZ",
    "zh": "乌兹别克斯坦",
    "nameIndex": "W",
    "pinyin": "wuzibiekesitan"
  }, {
    "code": 58,
    "tw": "委內瑞拉",
    "en": "Venezuela",
    "locale": "VE",
    "zh": "委内瑞拉",
    "nameIndex": "W",
    "pinyin": "weineiruila"
  }, {
    "code": 84,
    "tw": "越南",
    "en": "Vietnam",
    "locale": "VN",
    "zh": "越南",
    "nameIndex": "Y",
    "pinyin": "yuenan"
  }, {
    "code": 967,
    "tw": "也門",
    "en": "Yemen",
    "locale": "YE",
    "zh": "也门",
    "nameIndex": "Y",
    "pinyin": "yemen"
  }, {
    "code": 381,
    "tw": "南斯拉夫",
    "en": "Yugoslavia",
    "locale": "YU",
    "zh": "南斯拉夫",
    "nameIndex": "N",
    "pinyin": "nansilafu"
  }, {
    "code": 263,
    "tw": "津巴布韋",
    "en": "Zimbabwe",
    "locale": "ZW",
    "zh": "津巴布韦",
    "nameIndex": "J",
    "pinyin": "jinbabuwei"
  }, {
    "code": 243,
    "tw": "扎伊爾",
    "en": "Zaire",
    "locale": "ZR",
    "zh": "扎伊尔",
    "nameIndex": "Z",
    "pinyin": "zayier"
  }, {
    "code": 260,
    "tw": "贊比亞",
    "en": "Zambia",
    "locale": "ZM",
    "zh": "赞比亚",
    "nameIndex": "Z",
    "pinyin": "zanbiya"
  }]